# Generated by Django 2.2.7 on 2020-03-14 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подпись')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('sharing_type', models.CharField(choices=[('public', 'публичный'), ('closed', 'скрытый'), ('private', 'приватный')], default='public', max_length=10, verbose_name='Тип доступа')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('downloaded_count', models.IntegerField(default=0, verbose_name='Скачан')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузивший пользователь')),
            ],
        ),
    ]
