# Generated by Django 2.2.7 on 2020-03-14 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20200314_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='privately_accessed',
            field=models.ManyToManyField(related_name='private_files', to=settings.AUTH_USER_MODEL, verbose_name='Приватный доступ'),
        ),
    ]
