# Generated by Django 2.2.7 on 2020-03-14 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200314_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузивший пользователь'),
        ),
    ]
